---
title: "glottoTrees"
author: "Alexandru Craevschi"
date: "13 01 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(dplyr)
library(ape)
library(tidyverse)
library(phyloWeights)
library(glottoTrees)
library(ggcorrplot)
library(geiger)
library(rethinking)
```


```{r}
glotto_correspond <- read.csv("glottolog_correspondences.csv", sep = ";")
glotto_correspond
doculects <- glotto_correspond$Glottocode
```

```{r}
glotto <- data.table(get_glottolog_languages())
wowa_glotto <- glotto[glottocode %in% doculects]
```

```{r}
all_wowa <- abridge_labels(
  get_glottolog_trees(c("Indo-European", "Afro-Asiatic", 
                           "Kartvelian", "Turkic"))
)

all_wowa <- assemble_rake(all_wowa)
wowa_tips <- wowa_glotto$glottocode
all_wowa <- keep_tip(all_wowa, wowa_tips)

wowa_names <- as.character(glotto_correspond[,1])
glotto_wowa <- as.character(glotto_correspond[,2])

for (i in 1:length(all_wowa$tip.label)){
  tip_glotto <- all_wowa$tip.label[i]
  index <- match(tip_glotto, glotto_wowa)
  all_wowa$tip.label[i] <- wowa_names[index]
}

```


```{r}
phylo.corr <- vcv.phylo(all_wowa, corr = TRUE)
ggcorrplot(phylo.corr, lab = T)
plot(all_wowa)

#write_rds(all_wowa, "df_phylo_glotto_no_scale.rds")
```

```{r}

all_wowa <- abridge_labels(
  get_glottolog_trees(c("Indo-European", "Afro-Asiatic", 
                           "Kartvelian", "Turkic"))
)

all_wowa <- assemble_rake(all_wowa)
############# SCALING ####################
all_wowa <- rescale(all_wowa, model = "delta", 0.65)

wowa_tips <- wowa_glotto$glottocode
all_wowa <- keep_tip(all_wowa, wowa_tips)

# Replace labels in the tree with names of WOWA
wowa_names <- as.character(glotto_correspond[,1])
glotto_wowa <- as.character(glotto_correspond[,2])

for (i in 1:length(all_wowa$tip.label)){
  tip_glotto <- all_wowa$tip.label[i]
  index <- match(tip_glotto, glotto_wowa)
  all_wowa$tip.label[i] <- wowa_names[index]
}

# Normalize branch lengths and map them to interval [0, 1]
phylo.corr <- vcv.phylo(all_wowa, corr = T)

# Visualization of the results
ggcorrplot(phylo.corr, lab = T)
plot_glotto(all_wowa, nodelabels = F)
```

```{r}

all_wowa <- abridge_labels(
  get_glottolog_trees(c("Indo-European", "Afro-Asiatic", 
                           "Kartvelian", "Turkic"))
)

all_wowa <- assemble_rake(all_wowa)
############# SCALING ####################
all_wowa <- rescale(all_wowa, model = "delta", 1.25)

wowa_tips <- wowa_glotto$glottocode
all_wowa <- keep_tip(all_wowa, wowa_tips)

# Replace labels in the tree with names of WOWA
wowa_names <- as.character(glotto_correspond[,1])
glotto_wowa <- as.character(glotto_correspond[,2])

for (i in 1:length(all_wowa$tip.label)){
  tip_glotto <- all_wowa$tip.label[i]
  index <- match(tip_glotto, glotto_wowa)
  all_wowa$tip.label[i] <- wowa_names[index]
}

# Normalize branch lengths and map them to interval [0, 1]
phylo.corr <- vcv.phylo(all_wowa, corr = T)

# Visualization of the results
ggcorrplot(phylo.corr, lab = T)
plot_glotto(all_wowa, nodelabels = F)
```

```{r}
all_wowa <- abridge_labels(
  get_glottolog_trees(c("Indo-European", "Afro-Asiatic", 
                           "Kartvelian", "Turkic"))
)

all_wowa <- assemble_rake(all_wowa)
############# SCALING ####################
all_wowa <- rescale(all_wowa, model = "kappa", 0.5)

wowa_tips <- wowa_glotto$glottocode
all_wowa <- keep_tip(all_wowa, wowa_tips)

# Replace labels in the tree with names of WOWA
wowa_names <- as.character(glotto_correspond[,1])
glotto_wowa <- as.character(glotto_correspond[,2])

for (i in 1:length(all_wowa$tip.label)){
  tip_glotto <- all_wowa$tip.label[i]
  index <- match(tip_glotto, glotto_wowa)
  all_wowa$tip.label[i] <- wowa_names[index]
}

# Normalize branch lengths and map them to interval [0, 1]
phylo.corr <- vcv.phylo(all_wowa, corr = T)

# Visualization of the results
ggcorrplot(phylo.corr, lab = T)
plot_glotto(all_wowa, nodelabels = F)
```

```{r}
all_wowa <- abridge_labels(
  get_glottolog_trees(c("Indo-European", "Afro-Asiatic", 
                           "Kartvelian", "Turkic"))
)

all_wowa <- assemble_rake(all_wowa)
############# SCALING ####################
all_wowa <- rescale(all_wowa, model = "kappa", 1.5)

wowa_tips <- wowa_glotto$glottocode
all_wowa <- keep_tip(all_wowa, wowa_tips)

# Replace labels in the tree with names of WOWA
wowa_names <- as.character(glotto_correspond[,1])
glotto_wowa <- as.character(glotto_correspond[,2])

for (i in 1:length(all_wowa$tip.label)){
  tip_glotto <- all_wowa$tip.label[i]
  index <- match(tip_glotto, glotto_wowa)
  all_wowa$tip.label[i] <- wowa_names[index]
}

# Normalize branch lengths and map them to interval [0, 1]
phylo.corr <- vcv.phylo(all_wowa, corr = T)

# Visualization of the results
ggcorrplot(phylo.corr, lab = T)
plot_glotto(all_wowa, nodelabels = F)
```

```{r}
all_wowa <- abridge_labels(
  get_glottolog_trees(c("Indo-European", "Afro-Asiatic", 
                           "Kartvelian", "Turkic"))
)

all_wowa <- assemble_rake(all_wowa)
############# SCALING ####################
all_wowa <- rescale(all_wowa, model = "delta", 1.5)

wowa_tips <- wowa_glotto$glottocode
all_wowa <- keep_tip(all_wowa, wowa_tips)

# Replace labels in the tree with names of WOWA
wowa_names <- as.character(glotto_correspond[,1])
glotto_wowa <- as.character(glotto_correspond[,2])

for (i in 1:length(all_wowa$tip.label)){
  tip_glotto <- all_wowa$tip.label[i]
  index <- match(tip_glotto, glotto_wowa)
  all_wowa$tip.label[i] <- wowa_names[index]
}

# Normalize branch lengths and map them to interval [0, 1]
phylo.corr <- vcv.phylo(all_wowa, corr = T)

# Visualization of the results
ggcorrplot(phylo.corr, lab = T)
plot_glotto(all_wowa, nodelabels = F)
```

```{r}
all_wowa <- abridge_labels(
  get_glottolog_trees(c("Indo-European", "Afro-Asiatic", 
                           "Kartvelian", "Turkic"))
)

all_wowa <- assemble_rake(all_wowa)
############# SCALING ####################
all_wowa <- rescale(all_wowa, model = "lambda", 0.5)

wowa_tips <- wowa_glotto$glottocode
all_wowa <- keep_tip(all_wowa, wowa_tips)

# Replace labels in the tree with names of WOWA
wowa_names <- as.character(glotto_correspond[,1])
glotto_wowa <- as.character(glotto_correspond[,2])

for (i in 1:length(all_wowa$tip.label)){
  tip_glotto <- all_wowa$tip.label[i]
  index <- match(tip_glotto, glotto_wowa)
  all_wowa$tip.label[i] <- wowa_names[index]
}

# Normalize branch lengths and map them to interval [0, 1]
phylo.corr <- vcv.phylo(all_wowa, corr = T)

# Visualization of the results
ggcorrplot(phylo.corr, lab = T)
plot_glotto(all_wowa, nodelabels = F)
```

```{r}
all_wowa <- abridge_labels(
  get_glottolog_trees(c("Indo-European", "Afro-Asiatic", 
                           "Kartvelian", "Turkic"))
)

all_wowa <- assemble_rake(all_wowa)
############# SCALING ####################
all_wowa <- rescale(all_wowa, model = "kappa", 1.25)
all_wowa <- rescale(all_wowa, model = "delta", 0.75)

wowa_tips <- wowa_glotto$glottocode
all_wowa <- keep_tip(all_wowa, wowa_tips)

# Replace labels in the tree with names of WOWA
wowa_names <- as.character(glotto_correspond[,1])
glotto_wowa <- as.character(glotto_correspond[,2])

for (i in 1:length(all_wowa$tip.label)){
  tip_glotto <- all_wowa$tip.label[i]
  index <- match(tip_glotto, glotto_wowa)
  all_wowa$tip.label[i] <- wowa_names[index]
}

# Normalize branch lengths and map them to interval [0, 1]
phylo.corr <- vcv.phylo(all_wowa, corr = T)

# Visualization of the results
ggcorrplot(phylo.corr, lab = T)
plot_glotto(all_wowa, nodelabels = F)

```







