---
title: "wowa_brms"
author: "Alexandru Craevschi"
date: "29 11 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggcorrplot)
library(geodist)
library(ggplot2)
library(ggmap)
library(gmapsdistance)
library(tidyverse)
library(patchwork)
library(lingtypology)

## To reproduce the analysis, please register and set your own Google Maps API key. 
### This is free of cost.
#### Then, use the following line to set the API key 
#set.api.key("")
```


```{r}
wowa <- readRDS("wowa_recoded.rds")

distances <- matrix(0, nrow = 24, ncol = 24)
colnames(distances) <- unique(wowa$doculect)
rownames(distances) <- unique(wowa$doculect)

```

```{r}
# Slightly jitter northern+ankara to avoid complete overlap with Turkish from ankara

wowa[doculect == "northern+ankara"]$latitude <- wowa[doculect == "northern+ankara"]$latitude + 0.05
wowa[doculect == "northern+ankara"]$longitude <- wowa[doculect == "northern+ankara"]$longitude + 0.05

# The coordinates for Musandam are a bit inaccurate, so Google complains
wowa[doculect == "musandam"]$latitude[1] <- 26.00
wowa[doculect == "musandam"]$longitude[1] <- 56.18
```


```{r}
for (i in 1:24){
  doc <- unique(wowa$doculect)[i]
  lat.i <- wowa[doculect == doc]$latitude[1]
  long.i <- wowa[doculect == doc]$longitude[1]
  coordinates.i <- paste(as.character(lat.i), as.character(long.i), sep = "+")
  for (j in 1:24){
    if (i != j){
      other_doc <- unique(wowa$doculect)[j]
      lat.j <- wowa[doculect == other_doc]$latitude[1]
      long.j <- wowa[doculect == other_doc]$longitude[1]
      coordinates.j <- paste(as.character(lat.j), as.character(long.j), sep = "+")
      distances[i ,j] <- gmapsdistance(origin = coordinates.i,
                                       destination = coordinates.j,
                                       mode = "walking")$Distance 
    }
  }
}

### Save the results
# saveRDS(distances, "walking_distances.rds")
```






